mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import mysite.views 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^$', 'mysite.views.home', name='home'),
    url(r'^contact/$', mysite.views.ContactView.as_view(), name='contact'),
    url(r'^contact/thanks$', 'mysite.views.thanks', name='contactthanks'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^skyrim/', include('sky_alchemy.urls', namespace='skyrim')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sky_alchemy/urls.py
from django.conf.urls import patterns, url

from sky_alchemy import views

#the $ signs indicate end of string, so important to include
#to make sure that the 1st one doesnt just match everything.
#the (?P<name>\d+) matches a number (1 or more digits), and stores
#them in the variable name.
urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^ingredients$', views.ingredients, name='ingredients'),
)

sky_alchemy/models.py
from django.db import models

# Create your models here.



class Effect(models.Model):
    name = models.CharField(max_length=100, unique=True) #add uniqueness
    base_cost = models.FloatField()
    base_magnitude = models.FloatField()
    base_Duration = models.FloatField()
    
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ["name"]

        
class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True)
    effect1 = models.ForeignKey(Effect, related_name='effect1')
    effect2 = models.ForeignKey(Effect, related_name='effect2')
    effect3 = models.ForeignKey(Effect, related_name='effect3')
    effect4 = models.ForeignKey(Effect, related_name='effect4')
    cost = models.FloatField()
    weight = models.FloatField()
            
    def __unicode__(self):
        return self.name
        
    class Meta:
        ordering = ["name"]

mysite/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

class ContactForm(forms.Form):
    your_name = forms.CharField()
    your_email = forms.EmailField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    
    def send_email(self):
        try:
            subject = self.cleaned_data.get('subject')
            message = self.cleaned_data.get('message')+"\n\n sender: " + self.cleaned_data.get('your_name') + "\n\n " + self.cleaned_data.get('your_email')
            from_address = settings.EMAIL_HOST_USER
        except Exception,e:
            print str(e)
        try:

            send_mail(subject, 
                      message,
                      from_address, 
                      ['leo.van.nierop@gmail.com'], 
                      fail_silently=False)
          
        except Exception, e:
            print str(e)
        

mysite/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.views.generic.edit import FormView

def home(request):
    return render(request, "mysite/base.html")
 
def thanks(request):
    return render(request, "mysite/thanks.html")
 
class ContactView(FormView):
    template_name = "mysite/contact.html"
    form_class = ContactForm
    success_url = "/contact/thanks"
    
    def form_valid(self, form):
        form.send_email()
        return super(ContactView, self).form_valid(form)

sky_alchemy/views.py
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
import json

from sky_alchemy.models import Effect, Ingredient
# Create your views here.



def index(request):
    #retrieve list of ingredients
    #and display it with some form 
    #elements 
    return render(request, 'sky_alchemy/index.html')
    
def ingredients(request):
    all_ingredients = Ingredient.objects.all()
    datalist = []
    for ingredient in all_ingredients:
        datalist.append({"name": ingredient.name, "effects": [ingredient.effect1.name, ingredient.effect2.name, ingredient.effect3.name, ingredient.effect4.name]})
    data = json.dumps(datalist)
    return HttpResponse(data, content_type="application/json")

sky_alchemy/templates/sky_alchemy/index.html
{% extends "mysite/base.html" %}
{% block htmltagoptions %}
<html ng-app="skyrimjs">
{% endblock %}

{% load staticfiles %}

{% block pageheader %}
    <div class="container">
        <h1> Skyrim Alchemy App </h1>
    </div><!--closes Pagetitle-->
{% endblock %}

{% block maincontent %}
{% verbatim %}
<div>
    <button type="button" class="btn btn-info btn-xs" data-toggle="collapse" data-target="#instructions">
        instructions
    </button>
    <div id="instructions" class="collapse">
        <p>The best way to use this app is to start using it with a new character. You can select
        ingredients from the list on the left to get your character's ingredients matched up in 
        the app. When you make a potion, click make in the app and your knowledge of effects
        gets updated right away. </p>
        <p>You can add knowledge of ingredient effects by hand, if nessessary (eg because of eating 
        ingredients), by clicking "show effects". The reset effects button clears your complete
        knowledge of effects. </p>
        <p>The bottom panel gives the best suggestion of potions that teach you new effects most
        efficiently.</p>
        <p>The safe progress button allows you to keep track of a single character's knowledge of
        effects. It is stored as a cookie, so you do not get your progress in different browsers.
        This is a non-tracking cookie, activated by yourself. This is your warning for European 
        cookie laws.</p>
    </div>
</div>
<div ng-controller="alchemy as alch">
    <div class="row">
        <div class="wrapper">
            <div class="col-sm-4 scroll">
                <h4>Existing ingredients</h4>
                <button ng-click="showEffects=!showEffects"><span ng-show="showEffects">Hide</span><span ng-hide="showEffects">Show</span> Effects</button>
                <button ng-click="resetKnownEffects()">Reset effects</button>
                <select ng-model="selectIngredientSet">
                    <option value="all" selected>all</option>
                    <option value="a">a</option>
                    <option value="b">b</option>
                    <option value="c">c</option>
                    <option value="d">d</option>
                    <option value="e">e</option>
                    <option value="f">f</option>
                    <option value="g">g</option>
                    <option value="h">h</option>
                    <option value="i">i</option>
                    <option value="j">j</option>
                    <option value="k">k</option>
                    <option value="l">l</option>
                    <option value="m">m</option>
                    <option value="n">n</option>
                    <option value="o">o</option>
                    <option value="p">p</option>
                    <option value="q">q</option>
                    <option value="r">r</option>
                    <option value="s">s</option>
                    <option value="t">t</option>
                    <option value="u">u</option>
                    <option value="v">v</option>
                    <option value="w">w</option>
                    <option value="x">x</option>
                    <option value="y">y</option>
                    <option value="z">z</option>
                </select>
                <h1 ng-hide="ingredients"><strong>Loading Ingredients</strong></h1>
                <ul ng-repeat="ingredient in ingredients track by $index">
                    <li ng-show="selectIngredientSet==='all'|| ingredient.name.toLowerCase().indexOf(selectIngredientSet)===0">{{ingredient.name}}</br>
                        <ul ng-repeat="effect in ingredient.effects track by $index" ng-show="showEffects">
                            <li><input type="checkbox" ng-model="knownEffects[$parent.$index][$index]" ng-change="sortLearned()">{{effect}}</li>
                        </ul> 
                        <button class="btn btn-success btn-xs" ng-click="addIngredients($index, 1)">add 1</button>
                        <button class="btn btn-success btn-xs" ng-click="addIngredients($index, 5)">add 5</button>
                        <button class="btn btn-success btn-xs" ng-click="addIngredients($index, 10)">add 10</button>
                    </li>       
                </ul>
            </div>
            <div class="col-sm-4 scroll">
                <h4>Owned ingredients</h4>
                <button ng-click="clearOwned()">Clear</button>
                <button ng-click="saveProgress()">Save Character</button>
                <button ng-click="loadProgress()">Load Character</button>
                <ul ng-repeat="ingredient in ingredients track by $index">
                    <li ng-show="ingredient.owned"> {{ingredient.owned}} of {{ingredient.name}}</br>
                    <button class="btn btn-danger btn-xs" ng-click="addIngredients($index, -1)">del 1</button>
                    <button class="btn btn-danger btn-xs" ng-click="addIngredients($index, -5)">del 5</button>
                    <button class="btn btn-danger btn-xs" ng-click="addIngredients($index, -10)">del 10</button>
                    </li>
                </ul>
            </div>
            <div class="col-sm-4 scroll">
                <h4>Possible potions</h4>
                <button ng-click="showPotionDetails = !showPotionDetails">details</button>
                <h5>Two ingredients:</h5>
                <ul ng-repeat="potion in potions.twoIngredient track by $index">
                    <li>
                        {{ingredients[potion.ingredient1].name}} + {{ingredients[potion.ingredient2].name}}</br>
                        effects: <span ng-hide="showPotionDetails">{{potion.effects.length}}</span>
                        <ul ng-repeat="effect in potion.effects" ng-show="showPotionDetails" >
                            <li>{{effect}}</li>
                        </ul>
                        learned: <span ng-hide="showPotionDetails" >{{potion.learnnew()}}</span>
                        <ul ng-repeat="learned in potion.learneffects track by $index" ng-show="showPotionDetails">
                            <li ng-hide="knownEffects[learned[0]][learned[1]]">{{ingredients[learned[0]].name}}:{{ingredients[learned[0]].effects[learned[1]]}}</li>
                        </ul>
                        <button class="btn btn-primary btn-xs" ng-click="makePotion(potion)">make</button>
                    </li>
                    
                </ul>
                <h5>Three ingredients:</h5>
                <ul ng-repeat="potion in potions.threeIngredient track by $index">
                    <li>
                        {{ingredients[potion.ingredient1].name}} + {{ingredients[potion.ingredient2].name}} + {{ingredients[potion.ingredient3].name}}</br>
                        effects: <span ng-hide="showPotionDetails">{{potion.effects.length}}</span>
                        <ul ng-repeat="effect in potion.effects track by $index" ng-show="showPotionDetails" >
                            <li>{{effect}}</li>
                        </ul>
                        learned: <span ng-hide="showPotionDetails" >{{potion.learnnew()}}</span>
                        <ul ng-repeat="learned in potion.learneffects track by $index" ng-show="showPotionDetails" >
                            <li ng-hide="knownEffects[learned[0]][learned[1]]">{{ingredients[learned[0]].name}}:{{ingredients[learned[0]].effects[learned[1]]}}</li>
                        </ul>
                        <button class="btn btn-primary btn-xs" ng-click="makePotion(potion)">make</button>
                    </li>                  
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <h4>Top learning potions</h4>
            <ul ng-repeat="potion in top_potions() track by $index">
                <li ng-show="potion">
                    <button class="btn btn-primary btn-xs" ng-click="makePotion(potion)">make</button>
                    {{ingredients[potion.ingredient1].name}} + {{ingredients[potion.ingredient2].name}} 
                    <span ng-show="potion.ingredient3"> + {{ingredients[potion.ingredient3].name}} </span>
                    effects: {{potion.effects.length}}
                    learned: {{potion.learnnew()}}
                    
                </li>                  
            </ul>
        </div>
    </div>
    <div style="display:block;clear:both;"></div>
</div>
{% endverbatim %}

{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.min.js"></script>
<script src="{% static 'sky_alchemy/js/sky_app.js' %}"></script>
{% endblock %}
    
{% endblock %}

templates/mysite/base.html
<!DOCTYPE html>
{% block htmltagoptions %}
<html>
{% endblock %}
    <head>
        <title>{% block title %} Leo van Nierop's Django powered personal website{% endblock %}</title>
        {% load staticfiles %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">       
        {% block mycssfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'base/css/style.css' %}" />
        {% endblock %}
    </head>
    <body>       
        {% block menubar %}
            <div class=nav>
                <div class="navbar navbar-inverse navbar-static-top">
                    <div class="container">
                        <a href="{% url 'home' %}" class="navbar-brand">Home</a>
                        <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div class="collapse navbar-collapse navHeaderCollapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="{% url 'skyrim:index' %}">Skyrim Alchemy app</a></li>
                                <li><a href="{% url 'contact' %}">Contact me</a></li>
                            </ul>
                            
                        </div>
                    </div>
                </div><!--closes navbar-->
            </div>
        {% endblock %}
            
        <header>
            {% block pageheader %}
            <div class="container">
                <h1> Welcome to Leo van Nierop's Django powered personal website </h1>
            </div><!--closes Pagetitle-->
            {% endblock %}    
        </header>
        
        <div class="container">
            {% block maincontent %}
            <h1>Introduction</h1>
            <div class="row">
                <div class="col-xs-12">
                     <div class="col-xs-6"><img src={% static "base/images/LeoFoto.png" %} alt="Site owner picture" class="img-responsive"></div>                  
                
                    <h2>Leo and Work</h2>
                    <p>Welcome to my personal web page. Allow me to introduce myself: my name is Leo van Nierop. 
                    I am a particle physicist turned web developer, and this website is part of this transition. 
                    My field of study was on the interface of particle physics and cosmology. In particular, together 
                    with my supervisor, <a href="http://www.physics.mcmaster.ca/~cburgess/cburgess/">Cliff Burges</a>, 
                    and co-student (is that a word?) 
                    <a href="http://www.kuleuven.be/wieiswie/nl/person/00099126">Matt Williams</a>, we attempted to 
                    tackle the Cosmological Constant problem. For those not in the know: the cosmological constant is a 
                    parameter in our model for the universe that drives the universe to expand faster and faster. It has 
                    been measured by looking at the velocities of distant galaxies. It can also be predicted by calculating 
                    the energy of empty space (which, in quantum mechanics, is not zero). The problem, then, is that the 
                    calculated value is about 40 orders of magnitude (10000000000000000000000000000000000000000 times) 
                    larger than the measured value. For a good review about the problem, and some notes on our take on a 
                    solution, check out <a href="http://arxiv.org/abs/1309.4133">this</a> paper (very math-y, be warned).
                    </p>
                    <p>After trying my hand at academic research I have found that such a career is cool to talk about, 
                    but for me ultimately unsatisfactory. This is why I have been looking into a career that involves 
                    building or improving a product that will be actively used by (hopefully many) customers. When 
                    (fingers crossed) I acquire a work permit, I will start working at 
                    <a href="https://massuni.com/">Massuni</a> custom furniture design. Look at the demo, it is really 
                    cool! I'll wait for you, don't worry.
                    </p>
                    <p>Now that we are all on the same page (you did watch the video, didn't you?), that is what I will 
                    be spending the majority of my time on for the foreseeable future. This leaves me in a position where I 
                    have to quickly get familiar with a whole technology stack for dynamical websites. Luckily for me, Django 
                    was developed in an environment with harsh deadlines, so it was made mainly to get things done, NOW! If 
                    you are also looking for a place to start with web development, and you are partial to Python 
                    (or impartial to programming languages), a good place to start is the 
                    <a href="https://www.djangoproject.com/">Django</a> homepage, do the tutorial, and then work through 
                    the docs.
                    </p>
                    
                    <h2>Leo and Play</h2>
                    <p>Here's the problem with my hobbies: they're not very exciting to write about, and I have about 
                    zero pictures of them. The main reason for that is that when I am doing something I like, why would I then 
                    waste time spent on enjoying myself by taking pictures? From that statement, of course, you know 
                    photography is not one of those hobbies... 
                    </p>
                    <p>One constant in my free time is that I love playing games. Computer games, board games, card games: 
                    everything. I especially have a sweet spot for strategic games. I am a long time (on and off) fan of 
                    <a href="http://magic.wizards.com/">Magic</a>. I have spent more hours on 
                    <a href="http://www.elderscrolls.com/skyrim">Skyrim</a> then I dare to recount (hence the skyrim alchemy 
                    app in my links: a practise project to get the hang of things). I used to be an avid 
                    ping pong player, but this has taken a back seat the last few years mostly due to frequent moving. I 
                    intent to at least look into the options of picking that up again once I am settled in Toronto. 
                    </p>
                    <p>I read and watch a lot of science fiction and fantasy. I am particularly fond of near future dystopian 
                    scifi, such as <a href="http://www.williamgibsonbooks.com/">William Gibson's</a> Neuromancer. A lot of 
                    the concepts of Gibson's worlds are allready coming to life. We are relying more on technology than ever, 
                    and there is a strong trend in the economy of catch up or lose. Of course traditional jobs are still very 
                    much around, but for anyone my age I would advice them not to rely on this being true all the way until 
                    retirement!
                    </p>
                </div>
            </div>
        {% endblock %}
        </div>

    {% block javascript %} 
    {% endblock %}
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    </body>    
</html>

templates/mysite/contact.html
{% extends "mysite/base.html" %}
{% load staticfiles %}

{% block maincontent %}
<form action="" method="post">
{% csrf_token %}
    <ul>
    {{form.as_ul}}
    <input type="submit" value="Send" />
    <ul>
<form>
{% endblock %}

templates/mysite/thanks.html
{% extends "mysite/base.html" %}
{% load staticfiles %}

{% block maincontent %}
    Thanks, your message was sent.
{% endblock %}